### ISSUE TITLE
union(with: ) appears to be broken

### ISSUE THREAD

**Issue by nferruzzi** [troughton/Substrate#3]
https://github.com/troughton/Substrate/blob/987832dd60f46a863a53eb3fbed51167a2853a9a/Sources/SubstrateMath/Primitives.swift#L226

hello Thomas, while debugging I noticed that the 2 function `union(with:)` compute the union using the minimum of the maximum points, shouldn't it be the maximum? 

thanks in advance

**Comment by troughton** [comment]
Sorry about that; fixed in https://github.com/troughton/Substrate/commit/9032c9c224830c8d77cf35f60eddb6fda23d267c.
